version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
        SA_PASSWORD: "Pass@w0rd"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"
